from common import *
def main():
    summary=json.loads((OUT/'forecast_summary.json').read_text('utf-8'));bridge=json.loads((OUT/'bridge_summary.json').read_text('utf-8'))
    decomp=pd.read_csv(OUT/'decomposition_changes.csv');validation=pd.read_csv(OUT/'rolling_metrics.csv');rob=pd.read_csv(OUT/'robustness_variants.csv');pred=pd.read_csv(OUT/'forecast_12m_24m.csv');f=pd.read_csv(OUT/'frontier_family.csv');bench=pd.read_csv(OUT/'benchmark_robustness.csv')
    write(SPEC/'Q4_SCALE_NONSCALE_DECOMPOSITION_v1.md','# Q4 parameter-scale / residual decomposition v1\n\nACTIVE restricted descriptive result. Full N–D scale and true non-scale percentages NOT IDENTIFIED: only 9 primary D entries, including post-training and estimates.\n\n'+mdtable(decomp)+'\n\nS(t)=beta logN at the SAME two quantile-interpolation records; R(t)=F(t)-S(t), so endpoint changes add exactly. Primary 17.0233% parameter association / 82.9767% residual. This residual includes omitted D, post-training, family composition, selection, noise and possible technology, NOT causal technical progress. The earliest window has only 16 records; changing its definition changes the shares. Family bootstrap conditional coefficient-only share interval: '+str(summary['cluster_bootstrap_parameter_share95'])+'; endpoints fixed, not total decomposition uncertainty. Family-controlled row time slope 4.57404 points/year; pooled 5.14488. Same-family time signs differ (Gemma/Yi negative). Full-history descriptive coefficients do not enter rolling forecasting.\n\nHistorical endpoint change and fitted temporal slope are distinct: parameter endpoint change +2.70325 points but all-window S slope is -0.0297394 point/week. Neither can be substituted for the other. The residual slope is +0.284911 point/week, but it cannot identify D-adjusted technical progress. N-only/pooled/family endpoint shares are close; screening/window/start sensitivities can reverse the sign.\n')
    write(SPEC/'Q4_ROLLING_VALIDATION_v1.md','# Q4 rolling-origin validation v1\n\nSelected logit-linear by equal-horizon MAE; persistence not within 5% of best.\n\n'+mdtable(validation)+'\n\nMinimum 16 weekly endpoints. 26/52-week validation unavailable, not passed. All target windows use evaluation dates <= endpoint and dynamic fits only use observations through origin. Overlapping windows and folds are dependent. Current snapshot/license screening and latest revisions imply retrospective pseudo-out-of-sample; not a live historical leaderboard recreation. Validation is reused for model selection; no independent final test or post-selection interval guarantee. Fixed-midpoint AIC does not favor a break (45.61 linear vs47.50 broken); this short/dependent series has low break-detection power.\n')
    base=pred[pred.scenario=='BASELINE'][['target','central','lower95_conditional','upper95_conditional','horizon_weeks_from_data']]
    write(SPEC/'Q4_FORECAST_12M_24M_v1.md','# Q4 12/24-month conditional forecasts v1\n\nForecast origin **2026-09-25 Asia/Shanghai**, verified clock 2026-09-25 02:20:43 UTC. Last evaluation **2025-03-14**; gap **560 days**. Target is the 28-day q90 of C8 raw six-score average, on 0–100, not the normalized C1 average or absolute record maximum.\n\n'+mdtable(base)+'\n\nBoth horizons are EXTRAPOLATION-DOMINATED; the model extends about 30/42 months beyond last data, despite only nine months of historical coverage. Intervals are conditional on stationary residuals, four-week block and diffusion assumptions; 12/24-month empirical coverage is unavailable. The selected logit mathematical ceiling imposes saturation, not empirically established technological saturation.\n\nCONSERVATIVE / BASELINE / ACCELERATED retain 0 / 0.5 / 1 of positive extrapolated parameter-scale association. Estimated historical S trend is negative, so positive expansion A(h)=0 and all three scenarios collapse. This is a result of the frozen rule; no artificial scenario spread is invented. Full compute slowdown cannot be identified because D and industry resource paths are missing. No claim that technology is immune to compute constraints. Non-scale-proxy future contribution is conditional forecast minus assumed parameter component; residual includes omitted scale and selection.\n\nAll-model/scenario forecasts and last-data+12/+24 sensitivities are in forecast_all_models_scenarios.csv. Last-data targets are separate and never replace requested run-date targets. The Q3 51 conditional N/D/Loss paths are saved in Q3_conditional_interface.csv with benchmark_prediction NOT_IDENTIFIED; not used as future industry compute history.\n')
    rows=[]
    for r in summary['forecast']:rows.append({'target':r['target'],'conditional_statistical_PI95':str(r['conditional_PI95']),'model_range_NOT_CI':str(r['model_range']),'scenario_range_NOT_CI':str(r['scenario_range'])})
    write(SPEC/'Q4_UNCERTAINTY_ANALYSIS_v1.md','# Q4 uncertainty v1\n\n'+mdtable(pd.DataFrame(rows))+'\n\nA STATISTICAL: 1000 seeded circular four-week residual-block refits plus model-scale Gaussian diffusion SD*sqrt(1+h/4); percentile 2.5/97.5, bounded inverse link. Under explicit stationarity and diffusion assumptions only; process variance over long unobserved horizons is not estimated/validated by the data.\n\nB MODEL: central-prediction range of persistence, linear, logit and local-logit, all preregistered. Model-choice uncertainty is not merged into the statistical PI.\n\nC SCENARIO: retained positive parameter-scale growth 0/.5/1; collapsed because historical scale slope is negative. This scenario class is narrow and does not quantify all possible technical/compute futures. Missing D, source selection, benchmark contamination/redesign and future task relevance are unquantified structural uncertainty. No calibrated probability is attached to the scenario range. An unrestricted evidence-compatible future score could cover the full logical 0–100 range; the reported PI is conditional rather than an identified empirical bound.\n\nHistorical family-bootstrap coefficient/endpoint interval does not cover changing frontiers, unknown ancestry or missing D. The model with bounded link avoids >100 but its asymptote is mathematical, not evidence of real saturation.\n')
    cols=['variant','status','n','parameter_share','target','central']
    write(SPEC/'Q4_ROBUSTNESS_v1.md','# Q4 robustness v1\n\n'+mdtable(rob[cols])+'\n\n**Decomposition NOT STABLE across screening/time definitions.** Known-family, strict-license, later-start and 56-day cases reverse the parameter-share sign. Drop-largest-family forecast changes materially; unknown ancestry and merged-model composition remain unresolved. Base-only and post-trained subsets define different target populations and cannot be treated as uncertainty bounds for the pooled target. Release-date subset has too few eligible frontier endpoints; no fabricated alternate-date forecast. Submission-date sensitivity re-dates later evaluated scores and is explicitly retrospective, not a valid real-time holdout.\n\n'+mdtable(bench)+'\n\nAll six task frontiers improve over the primary endpoints, but magnitude varies strongly (MATH largest). This is broad score improvement, not evidence of causal technology. February 2025 has a large evaluation cluster (204 primary records in one week); exclude-Feb sensitivity remains positive but raises forecasts. C8 coverage is selected, not a random subset of the full open-weight ecosystem.\n')
    # Algebraically explicit scenario decomposition, with no double addition of residual trend.
    scen=pred.copy();s0=float(f.S.iloc[-1]);y0=float(f.F.iloc[-1]);scen['parameter_component']=s0+scen.retained_scale_fraction*np.maximum(0,scen.scale_slope_per_week*scen.horizon_weeks_from_data);scen['residual_component']=scen.central-scen.parameter_component;scen['delta_parameter']=scen.parameter_component-s0;scen['delta_residual']=scen.residual_component-(y0-s0);scen['component_status']='CONDITIONAL N-ONLY; residual includes omitted D; not causal';scen.to_csv(OUT/'scenario_decomposition.csv',index=False)
    # CP2 documentation failure did not affect any numerical output; record it explicitly.
    log=ROOT/'09_handoff/ROUND7_CHECKPOINT_LOG.md'
    with log.open('a',encoding='utf-8') as stream:stream.write('\nCP1 VERIFIED: f3f0a4e0dc34782a9f0a00da42fc21a85ca4ce4f = remote main.\nCP2 VERIFIED: 10c30f90549fe85f9ef298d9e965c651dc887e50 = remote main. Numerical outputs complete. Markdown generation lacked optional tabulate; replaced with deterministic local formatter at CP3, no model rerun.\nCP3: run-date 12/24 forecasts, separate uncertainty and robustness completed.\n')
if __name__=='__main__':main()
