from common import *
def main():
    a=json.loads((AUD/'Q4_DATA_AUDIT_METRICS_v1.json').read_text('utf-8'))
    write(AUD/'Q4_DATA_AUDIT_v1.md',f'''# Q4 data audit v1

ACTIVE / CHECKED — data audit only, before model fitting.

Official roles and every raw SHA are in Q4_C1_C10_ROLE_MATRIX_v1.json. PDF visible mapping rendered and inspected; near-white margin interference excluded. Raw files are read-only. Main input has {a['primary_rows']} exact-ID / parameter-checked C1–C8 records, evaluated {a['primary_dates'][0]} to {a['primary_dates'][1]}. C9 supplies hub availability and flagged status; no duplicate observations appended.

C1 has {a['C1_duplicate_IDs_excluded']} ambiguous normalized model IDs (162 rows); excluded rather than choosing the highest score. C2 core numeric cells differ from C1 in last-digit CSV roundoff and are not used as additional observations; exact deviations must be measured in final QA. C3 has {a['C3_historical_rows']} historical rows, {a['C3_historical_mean_mismatch_gt_1']} with average differing from six-dimension mean by >1 point. They are a comparability stress test, excluded from the homogeneous time model. Its 4573 leaderboard rows are another snapshot, not an independent longitudinal panel. No inference of benchmark redesign date from these mixed records.

C8: all {a['C8_files']} files parsed or failure recorded; {a['C8_parse_failures']} truncated files remain untouched. Latest parseable per directory: {a['C8_latest_directories']}; six-complete: {a['C8_latest_complete']}. Every BBH subtask is extracted and task mean/median/count/std calculated. C10 seven README files remain documentation, not evaluation evidence. C7 TB is not token count and maximum context is not actual training context.

C4 compute/data/open-weight fields are used in macro context and conservative name+parameter matching ({a['C4_matches']} matches). Token notes, estimated quantities and training-stage ambiguity remain visible. Main sample has only {a['primary_D_known']} nonmissing D values; some are post-training or estimated. They cannot support a population-wide N–D adjustment. The primary decomposition MUST be called PARAMETER-SCALE ASSOCIATION plus PARAMETER-ADJUSTED RESIDUAL, with D/compute-confounding unresolved. A true scale-versus-non-scale causal percentage is NOT IDENTIFIED.

C6 has 75 unique models; C5 43 IDs are a subset and never doubled. Only seven Pythia rows have high supplied comparability, not independent external provenance. Medium-comparability losses are not pooled into an absolute global bridge.

Snapshot survivorship, name-based family uncertainty, historical license availability and C8 coverage selection persist. The C8 six-raw-score composite is explicitly distinct from C1's normalized leaderboard average; no numeric interchangeability is assumed.
''')
    write(AUD/'Q4_ENTITY_RESOLUTION_v1.md','''# Q4 entity resolution v1

ACTIVE. Row-level table: 01_data/processed/modeling_phase4/round7/Q4_MODEL_ENTITY_RESOLUTION_v1.csv.

Canonical full model ID = Unicode-preserving lower-case and surrounding-space removal; no namespace, base/instruct, version or parameter suffix is dropped for C1–C8. All ambiguous C1 IDs excluded. Latest parseable C8 filename timestamp chosen per directory; revision recorded. Require C1/C8 N agreement within 2%. Family is a conservative recognized name token and can be unknown; it does not certify ancestry, especially for merged models. Type uses C1 pretrained / fine-tuned-chat / merge / other. Both evaluation, submission and C2 release dates are retained; no date filling across concepts.

C4 auxiliary matching uses unique punctuation-normalized terminal name and N within 10%; provenance notes and matching method preserved. This medium-confidence match is not a run-identity assertion or permission to transfer fine-tuning tokens to pretraining D. D_primary_usable additionally requires base type but remains source-reported/estimated. Missing values remain missing. C9 availability and explicit reported license must pass for primary eligibility; unknown/other/missing licenses excluded. Broad reported licenses permit open-weight research proxy including restricted licenses. Strict sensitivity permits only the preregistered permissive/copyleft list; no legal certification claimed.
''')
    write(SPEC/'Q4_BRIDGE_MODEL_SPEC_v1.md','''# Q4 bridge model and validation contract v1

ACTIVE / FROZEN before fitting, decision R7-SPEC-001 under explicit Round7 execution authorization. Researcher specification, no external Opus consensus claimed.

B0: no quantitative transport. B1: within-family nonincreasing linear Loss–score relation (slope constrained <=0) and monotone piecewise interpolation, compared with train-mean baseline. C6 high Pythia only; no duplicate C5 rows. C6 medium groups analyzed separately as local diagnostics only when >=4 distinct scales; no common absolute Loss pool or B3 global fit. B2 family-conditioned fit cannot establish transfer to an unseen family without common loss anchors and is NOT ELIGIBLE here.

Leave-one-scale-out for seven high rows; leave-lowest-two / highest-two-scale-region-out; rank Spearman(-Loss,score), family/scale residual CSV, and error against held-out train mean. Temporal holdout NOT IDENTIFIABLE: no per-row loss/benchmark paired timestamps; leave-one-family-out NOT IDENTIFIABLE in high stratum: one family. Report those failures of support, not PASS. High-label does not certify tokenization/run identity or loss timestamp; audit against B1 final checkpoint values and C1 score identity.

Precommitted Weak threshold: correct direction, Spearman >=0.7 and both LOO RMSE and each endpoint-region RMSE no worse than mean baseline; high pairs must be exact ID and N-compatible (<=2%) with C1. Strong additionally requires >=3 genuinely comparable loss families and successful family+time holdout, unavailable here. If neither qualified, verdict NO RELIABLE BRIDGE, retain only descriptive curve and B0 operationally. C6 LB_Average is normalized C1 space; cannot silently map it into C8 raw6 space. An additional exact-pair raw6 bridge requires >=5 high rows and same validation; otherwise unavailable.
''')
    write(SPEC/'Q4_FRONTIER_MODEL_SPEC_v1.md','''# Q4 frontier, decomposition and forecasting specification v1

ACTIVE / FROZEN before fitting. R7-SPEC-001. Seed 20260925. Scope explicitly qualified by missing D and short historical evaluation coverage.

Primary target: F(t) = linear-interpolated 90th percentile of the equal-weight mean of six C8 raw task-group scores, each in [0,100], among eligible models evaluated within (t-28d,t]. IFEval = mean(prompt-strict,instruction-strict); BBH/GPQA/MUSR = group acc_norm; MATH = group exact_match; MMLU-PRO = group acc. This raw6 composite is not C1 normalized Average. Minimum 15 unique models per window. Weekly Sunday endpoints from first evaluation to last complete Sunday; also terminal evaluation date for forecasting. A robust rolling cohort frontier may decline and is not an all-time record maximum. Latest parseable revision per model directory, no future revisions assigned to earlier dates. Licensed, hub-available, unflagged, six-complete C1–C8 exact IDs with N agreement <=2%; merge and post-training types retained and explicitly controlled. Unknown families retained and reported.

Decomposition D0: row-level OLS y = a + b log(N_B) + gamma time_years + type indicators + family indicators. Compare N-only, N+time+type (pooled), family-controlled, and same-family slopes. No D imputation, no causal interpretation. Frontier quantile is linear interpolation between two sorted observed scores; use exactly those same interpolation weights for S(t)=b log(N) and R(t)=F(t)-S(t). Changes satisfy deltaF=deltaS+deltaR exactly. Additive constants in S do not affect changes. Historical percentages are ratios of changes and may be negative or >100%; do not clamp. DeltaR includes D, post-training, family, noise, selection and true technical changes. Full N–D/non-scale contribution NOT IDENTIFIED. Descriptive full-history coefficients never used to construct rolling validation targets or train features.

Dynamics: persistence, clipped linear OLS, logit-linear OLS (epsilon=0.001 in proportions), local logit trend on last 13 weeks. Fit frontier series only. Rolling-origin at each available Sunday, >=16 weekly training endpoints, horizons 4/13/26/52 weeks where actual future observations exist; evaluate exact target endpoints. Expanding training only; no centered smoothing or future window entries. Short-horizon model selection = mean absolute error equally averaged across available horizons; persistence retained if within 5% of best. Models never selected on 12/24-month output. Overlapping 28d windows create dependence; pseudo-out-of-sample is retrospective evaluation-date forecasting, not a reconstructed live historical leaderboard. No 26/52-week validation claim if unavailable.

Structural diagnostics: first/second-half slope, midpoint broken-slope descriptive fit and AIC, weekly evaluation counts and family shares. Fixed midpoint avoids outcome-selected breaks. Local model already included; no unregistered change-point search.

Forecast origin 2026-09-25 Asia/Shanghai (clock verified); targets 2027-09-25 and 2028-09-25. Last observation is March 2025; extrapolation horizon includes this data gap. Also provide last-data+12/+24 months as separate conditional sensitivities, never substitute them for requested run-date targets. Both run-date forecasts are EXTRAPOLATION-DOMINATED; empirical long-horizon coverage unavailable.

Statistical uncertainty: B=1000 circular moving-block residual bootstrap, block length 4 weekly endpoints (reflects overlapping target windows); refit frozen model; add independent future model-scale normal shock with residual SD times sqrt(1+h/4), h in weeks from last data. Persistence uses SD of 4-step frontier increments and sqrt(1+h/4). Report percentile 2.5/97.5 bounds. This is a CONDITIONAL MODEL-BASED prediction interval under stationarity and diffusion assumptions, not verified real-world coverage. Use B=200 for rolling interval diagnostics. Clip score predictions to [0,100]; logit predictions inverse-transformed. Model uncertainty = range of four model central predictions; not CI.

Scenarios: let U(h) be selected dynamic forecast and A(h)=max(0,slope(S)*h) the extrapolated historical parameter-scale association. Baseline slowing scale = clip(U-0.5A); conservative = clip(U-A); accelerated relative to slowdown = clip(U) (historical scale trend maintained). Multipliers 0/0.5/1 are explicit retained-scale-path assumptions, not fitted probabilities or arbitrary score percentages. If A=0, scenarios coincide, without inventing separation. Report no-slowdown reference U and each removed parameter contribution; slow compute and slow parameter-scale growth are not empirically interchangeable when D is missing. Full compute-slowdown prediction remains unidentified. Non-scale residual historical slope/uncertainty and family sensitivity reported, not added again to U.

Robustness: six separate benchmark directions; strict licenses; drop largest recognized family; known families only; base vs post-trained; same-family trajectories; start 2024-09-01; 56d versus 28d window; q=.95; submission and available release dates strictly as retrospective sensitivities (scores evaluated later); February release/evaluation cluster exclusion. Q3 paths copied only as conditional N/D/Loss mechanism table; no score conversion without reliable bridge, no reuse as history or industry scale forecast. Support caps are not frontier saturation.

QA: check raw hashes, identity/duplicates, types/licenses, C8 complete groups and corruption exclusions, window causality, rolling target support, disjoint time splits, quantile/additive identities, bootstrap seed and bounds, all horizons/date gaps, scenario labels, no global Loss pool, result provenance and registries. No probabilistic guarantee or causal technology claim. Paper-ready means a qualified model package, not final paper formatting.
''')
    cfg={'decision':'R7-SPEC-001','run_id':'EXP-Q4-R7-20260925-v1','seed':20260925,'run_date':'2026-09-25','targets':['2027-09-25','2028-09-25'],'quantile':.9,'window_days':28,'minimum_models':15,'rolling_min_train':16,'rolling_horizons_weeks':[4,13,26,52],'models':['persistence','linear','logit','local_logit'],'bootstrap':1000,'rolling_bootstrap':200,'block_weeks':4,'scenario_retained_scale':[0,.5,1],'spec_sha256':{p.name:sha(p) for p in SPEC.glob('*SPEC*.md')},'input_manifest_sha256':sha(DATA/'INPUT_MANIFEST_v1.json')}
    dump(ROOT/'05_experiments/configs/Q4_R7_FROZEN_v1.json',cfg)
    with (ROOT/'09_handoff/DECISION_LOG.md').open('a',encoding='utf-8') as f:f.write('\nR7-SPEC-001 CONFIRMED researcher execution specification: C8 raw6 evaluation-date frontier, C1/C9 screen, C3 comparability audit, C4 scale coverage. N-only decomposition explicitly does not identify full N–D/non-scale causal percentages. Bridge B0 fallback and extrapolation-dominated forecasts precommitted. Specs frozen at CP1 before any fits.\n')
    with (ROOT/'05_experiments/EXPERIMENT_REGISTRY.md').open('a',encoding='utf-8') as f:f.write('\n## Round7 preregistration\n\nAUDIT-Q4-R7-20260925-v1 COMPLETED: round7_mapping.py + round7_audit.py, all C hashes, entities/C8 tasks/C3/C4.\nEXP-Q4-R7-20260925-v1 PLANNED: Q4_R7_FROZEN_v1.json; seed 20260925; processed/modeling_phase4/round7 INPUT_MANIFEST; code/modeling_phase4; outputs 06_results/raw/EXP-Q4-R7-20260925-v1. Model fitting starts only after CP1 freeze.\n')
if __name__=='__main__':main()
