from common import *
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
FIG=ROOT/'06_results/figures/round7';FIG.mkdir(parents=True,exist_ok=True)
plt.rcParams.update({'font.family':'DejaVu Sans','font.size':10,'axes.spines.top':False,'axes.spines.right':False,'figure.dpi':140,'savefig.dpi':180})
manifest=[]
def save(fig,num,claim,sources):
    name=f'FIG-Q4-R7-{num:03d}';fig.tight_layout()
    for ext in ['png','svg']:fig.savefig(FIG/f'{name}.{ext}',bbox_inches='tight')
    manifest.append({'id':name,'claim':claim,'sources':sources,'result_id':f'Q4-R7-{num:03d}','generator':'04_code/modeling_phase4/round7_figures.py','files':{str((FIG/f'{name}.{ext}').relative_to(ROOT)).replace('\\','/'):sha(FIG/f'{name}.{ext}') for ext in ['png','svg']}})
    plt.close(fig)
def main():
    d=pd.read_csv(DATA/'Q4_PRIMARY_v1.csv');f=pd.read_csv(OUT/'frontier_family.csv');dates=pd.to_datetime(f.date);forecast=pd.read_csv(OUT/'forecast_fan.csv');rob=pd.read_csv(OUT/'robustness_variants.csv');summ=json.loads((OUT/'forecast_summary.json').read_text('utf-8'))
    fig,ax=plt.subplots(figsize=(9,4.6));ax.scatter(pd.to_datetime(d.date),d.score,s=9,alpha=.23,color='#547aa5',label='Eligible evaluated models (n=853)');ax.plot(dates,f.F,color='#9c2f35',lw=2.5,label='28-day q90 frontier');ax.set(ylabel='C8 raw-six composite (0-100)',xlabel='Evaluation date',title='Observed robust frontier, June 2024 - March 2025');ax.legend(loc='upper left');save(fig,1,'Observed evaluation-cohort q90 improves; not an all-time record',['Q4_PRIMARY_v1.csv','frontier_family.csv'])
    fig,axs=plt.subplots(1,2,figsize=(10,4.5));axs[0].plot(dates,f.F-f.F.iloc[0],label='Observed change',lw=2);axs[0].plot(dates,f.S-f.S.iloc[0],label='Parameter association',lw=2);axs[0].plot(dates,f.R-f.R.iloc[0],label='Residual (D unobserved)',lw=2);axs[0].axhline(0,color='gray',lw=.7);axs[0].xaxis.set_major_locator(mdates.MonthLocator(interval=3));axs[0].xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'));axs[0].legend(fontsize=8);axs[0].set(ylabel='Change from first cohort (points)',title='Exact additive change accounting');dc=pd.read_csv(OUT/'decomposition_changes.csv');axs[1].bar(dc.model,dc.delta_S,label='Parameter');axs[1].bar(dc.model,dc.delta_R,bottom=dc.delta_S,label='Residual',color='#e1a451');axs[1].set(ylabel='Endpoint improvement (points)',title='N-only / pooled / family controls');axs[1].legend();fig.suptitle('Residual includes missing D, selection and technology; no causal share',fontsize=11);save(fig,2,'Parameter/residual decomposition is descriptive and incomplete',['decomposition_changes.csv','frontier_family.csv'])
    br=pd.read_csv(OUT/'bridge_residuals.csv');br=br[br.family=='HIGH_pythia'];bv=pd.read_csv(OUT/'bridge_validation.csv');bv=bv[(bv.family=='HIGH_pythia')&(bv.split=='LOSO')]
    fig,axs=plt.subplots(1,2,figsize=(9,4));axs[0].scatter(br.Loss,br.observed,s=45);so=br.sort_values('Loss');axs[0].plot(so.Loss,so.fitted,color='#b94d42');axs[0].set(xlabel='C6 / B1 attachment Loss',ylabel='C6 normalized LB Average',title='Seven high-comparability Pythia rows');axs[1].bar(bv.method,bv.rmse,color=['#b94d42','#547aa5','#e1a451']);axs[1].set(ylabel='Leave-one-scale-out RMSE',title='Mean baseline is not improved');fig.suptitle('NO RELIABLE BRIDGE - this is not the raw-six forecast scale',fontsize=11);save(fig,3,'Pythia bridge fails preregistered generalization tests',['bridge_residuals.csv','bridge_validation.csv'])
    val=pd.read_csv(OUT/'rolling_metrics.csv');fig,axs=plt.subplots(1,2,figsize=(9,4));colors=['#657383','#547aa5','#a8443e','#d59d42']
    for c,(m,g) in zip(colors,val.groupby('model')):axs[0].plot(g.horizon_weeks,g.MAE,'o-',label=m,color=c);axs[1].plot(g.horizon_weeks,g.coverage95,'o-',label=m,color=c)
    axs[0].set(xlabel='Horizon (weeks)',ylabel='MAE (points)',title='Retrospective rolling forecasts');axs[1].set(xlabel='Horizon (weeks)',ylabel='Conditional interval coverage',ylim=(0,1.05),title='Dependent folds; short horizons only');axs[0].legend(fontsize=8);axs[1].axhline(.95,color='gray',ls=':');fig.suptitle('No 26/52-week validation; no 12/24-month coverage claim',fontsize=11);save(fig,4,'Logit selected at 4 and 13 weeks; long-horizon validation absent',['rolling_metrics.csv'])
    fig,ax=plt.subplots(figsize=(10,4.8));ax.plot(dates,f.F,color='#284968',lw=2,label='Observed q90');fd=pd.to_datetime(forecast.date);ax.fill_between(fd,forecast.lower95,forecast.upper95,color='#c2d5e5',alpha=.8,label='95% conditional model PI');ax.plot(fd,forecast.central,color='#a8443e',lw=2,label='Selected logit extrapolation');ax.axvline(pd.Timestamp('2026-09-25'),color='#555',ls='--',label='Run-date forecast origin');ax.axvspan(dates.iloc[-1],pd.Timestamp('2026-09-25'),color='#ddd',alpha=.4,label='560-day unobserved gap');ax.set(ylim=(0,100),ylabel='C8 raw-six q90 (0-100)',title='12/24-month targets from 2026-09-25 are extrapolation-dominated');ax.legend(loc='lower right',fontsize=8);save(fig,5,'Conditional statistical fan does not include model/source uncertainty',['frontier_family.csv','forecast_fan.csv'])
    family=pd.read_csv(OUT/'same_family_trajectories.csv');fig,axs=plt.subplots(1,2,figsize=(10,4.4));axs[0].barh(family.family,family.time_score_per_year,color=['#a8443e' if x<0 else '#547aa5' for x in family.time_score_per_year]);axs[0].axvline(0,color='gray');axs[0].set(xlabel='N/type-adjusted score slope per year',title='Same-family directions vary');subset=rob[(rob.target=='2027-09-25')&rob.variant.isin(['drop_largest_llama','known_families','strict_license','posttrained_only','exclude_Feb_cluster'])];axs[1].scatter(subset.central,subset.variant,color='#a8443e');axs[1].axvline(summ['forecast'][0]['central'],color='#547aa5',ls='--');axs[1].set(xlabel='2027 conditional central prediction',title='Population sensitivity (not CI)');save(fig,6,'Family and population selection affect decomposition and forecast',['same_family_trajectories.csv','robustness_variants.csv'])
    fp=pd.read_csv(OUT/'forecast_all_models_scenarios.csv');fp=fp[(fp.origin_type=='RUN_DATE')&(fp.scenario=='BASELINE')];fig,axs=plt.subplots(1,2,figsize=(10,4))
    for ax,(target,g) in zip(axs,fp.groupby('target')):ax.scatter(g.central,g.model,color='#547aa5',s=45);ax.set(xlim=(0,100),xlabel='Central prediction (not interval)',title=target)
    fig.suptitle('Model uncertainty: plausible baselines disagree at long horizons',fontsize=11);save(fig,7,'Long-horizon model spread is separate from statistical intervals',['forecast_all_models_scenarios.csv'])
    scen=pd.read_csv(OUT/'scenario_decomposition.csv');fig,axs=plt.subplots(1,2,figsize=(10,4.4))
    for ax,(target,g) in zip(axs,scen.groupby('target')):
        ax.bar(g.scenario,g.delta_parameter,label='Parameter component',color='#547aa5');ax.bar(g.scenario,g.delta_residual,bottom=g.delta_parameter,label='Residual / omitted scale',color='#e1a451');ax.set(ylim=(0,40),title=target,ylabel='Change from last observed frontier');ax.tick_params(axis='x',labelsize=8)
    axs[0].legend(fontsize=8);fig.suptitle('Scale scenarios collapse: no positive historical S trend to slow',fontsize=11);save(fig,8,'Collapsed scenarios do not establish robustness to real compute slowdown',['scenario_decomposition.csv'])
    dump(FIG/'figure_manifest.json',manifest)
    fig,axs=plt.subplots(4,2,figsize=(16,14))
    for ax,r in zip(axs.flat,manifest):ax.imshow(plt.imread(FIG/(r['id']+'.png')));ax.axis('off')
    fig.tight_layout();fig.savefig(FIG/'contact_sheet.png',dpi=110);plt.close(fig)
    print('8 figures saved (PNG + SVG)')
if __name__=='__main__':main()
